version: '3'
services:
  svkeleton:
    image: svkeleton
    ports: 
      - "3333:3333"
    volumes:
       - ./src:/home/node/svkeleton/src
       # Uncomment if you wish to use static files: 
       #- ./static:/home/node/svkeleton/static

    # run the init script which will copy src and static files 
    # to local filesystem if necessary, then start the SvelteKit dev server:
    command: >
      sh -c "node init.cjs && 
             npm run dev"